version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.11

build:
  image: latest

formats: all

docs_dir: docs

python_install:
  use_system_site_packages: false

dependencies:
  # Add any dependencies required for building your documentation here
  - sphinx
  - sphinx-rtd-theme

whitelist:
  # Add paths to directories or files you want to include in the documentation build
  - README.md
  - docs/*
  # Add other necessary paths

# Settings for automatic building of documentation
autobuild:
  # Enable automatic building on changes to the project
  enabled: true

  # Specify the branches you want to build documentation for
  branches:
    only:
      - master # Only build docs for the master branch
